@startuml


class Board {
    -Piece[][] board, prev
    -Square whiteKing, blackKing
    -Move lastMove
    +String toString()
    +void makeMove(Move newMove)
    +void undo()
    -boolean hasLegalMoves(Color.color)
    -boolean isLegal(Move move)
    -canMakeMove(Square from, Square to)
    -isUnderAttack(Piece piece, Square sq)
    -pieceInDir(Square sq, Direction dir)
    -Piece[][] boardCopy()
}

class Piece {
    -PieceType type
    -Color color
    +Piece(Color color, PieceType type)
    +PieceType getType()
    +Color getColor()
    +boolean equals(Object o)
    +String toString()
    +Direction canMoveTo(Square dest)
}

class Move {
    -Piece piece
    -Square from
    -Square to
    +Move(String move, Color color)
    +Move(Piece piece, Square dest)
    +Piece getPiece()
    +Square getFrom()
    +Square getTo()
}

class Square {
    -int row
    -int col
    +Square(int row, int col)
    +Square(String sq)
    +int getRow()
    +int getCol()
}

enum Color {
    +BLACK
    +WHITE
}

enum Direction {
    +UP, DOWN, LEFT, RIGHT, UPRIGHT, UPLEFT,
    DOWNRIGHT, DOWNLEFT
    +int rowInc()
    +int colInc()
}

enum PieceType {
    +KING, QUEEN, ROOK, BISHOP, KNIGHT, PAWN
    +String toString()
    +canMove(Square from, Square to)
}

Board *- Move
Board *-- Square
Move *- Square
Piece *- Move
Board *-- Piece
Piece *-- PieceType
PieceType *- Direction
Color -* Piece

@enduml